name: Publish GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs